### PR TITLE
Refactor code style / Tests / Remove createContainer

### PR DESCRIPTION
**Pull request by LoicMahieu**
- Refactor code style: use of [`standard`](https://github.com/feross/standard) : One Style to Rule Them All :+1: 
- Add automated tests : currently using filesystem storage. Note for future: add .travis.yml
- Simplify `_handleFile` : only handle the file and upload it. This module should not be responsible about the container creation, even his existence.

### CODE REVIEW

**Comment by dustin-H** [comment]
Hi there,
thanks for your PR! I will review and merge soon!

Cheers
Dustin

**Comment by LoicMahieu** [comment]
Hi @dustin-H 
Did you find time to review ?

Sure it can be considered as breaking change due to the remove of `createContainer` in the upload process but I think it really not the job of this module.
I think a minor version change is enough: `npm version minor` will produces `1.1.0`

**Comment by dustin-H** [comment]
Hi,
I am in ski-holidays this week, coming back tomorow...

I already had a look on your work and totally agree, I will merge and pubilsh this weekend.

Cheers Dustin

**Comment by LoicMahieu** [comment]
Hi @dustin-H 
Sorry to disturb you during your vacation :) There is no emergency so take your time and enjoy your break :D
⛷

**Comment by dustin-H** [comment]
@LoicMahieu  Thanks!  :)

Just published npm v1.1.0!

**Pull request merged**
